# Generated by Django 5.0.2 on 2025-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataextract', '0002_alter_utilizationreport_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=255)),
                ('rdm', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('billing', models.CharField(max_length=255)),
            ],
        ),
    ]
