# Generated by Django 5.1.7 on 2025-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('administrative', models.FloatField()),
                ('billable_days', models.FloatField()),
                ('training', models.FloatField()),
                ('unassigned', models.FloatField()),
                ('vacation', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('last_week', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('addtnl_days', models.FloatField()),
                ('wtd_actual', models.FloatField()),
                ('spoc', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('spoc_comments', models.TextField(blank=True, null=True)),
                ('rdm', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('billing', models.FloatField()),
            ],
        ),
    ]
