# Generated by Django 5.1.7 on 2025-04-03 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizationreport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=50, unique=True)),
                ('industry', models.CharField(blank=True, choices=[('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=25, null=True)),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(max_length=7)),
                ('region', models.CharField(choices=[('ACS', 'ACS'), ('ANZ', 'ANZ'), ('APAC', 'APAC'), ('EMEA', 'EMEA'), ('ASEAN', 'ASEAN'), ('India', 'India'), ('LAD', 'LAD'), ('NAC', 'NAC')], max_length=50)),
                ('cluster', models.CharField(choices=[('ACS', 'ACS'), ('ANZ', 'ANZ'), ('ASEAN + Japan + Hongkong', 'ASEAN + Japan + Hongkong'), ('CSN', 'CSN'), ('CSS', 'CSS'), ('ESG', 'ESG'), ('Europe + Greece + Israel', 'Europe + Greece + Israel'), ('India North', 'India North'), ('India South', 'India South'), ('India West', 'India West'), ('MEO', 'MEO'), ('NAC + LAD', 'NAC + LAD'), ('NetSuite', 'NetSuite'), ('Saudi + Sub Sahara', 'Saudi + Sub Sahara'), ('Sub Sahara', 'Sub Sahara'), ('UK + IL', 'UK + IL')], max_length=50)),
                ('rdm', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=2)),
                ('ownership', models.CharField(blank=True, choices=[('OC', 'OC Owner'), ('GSC', 'GSC Owned'), ('TBD', 'TBD')], default='TBD', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('fcrm_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('industry', models.CharField(blank=True, choices=[('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=25, null=True)),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(max_length=7)),
                ('region', models.CharField(choices=[('ACS', 'ACS'), ('ANZ', 'ANZ'), ('APAC', 'APAC'), ('EMEA', 'EMEA'), ('ASEAN', 'ASEAN'), ('India', 'India'), ('LAD', 'LAD'), ('NAC', 'NAC')], max_length=50)),
                ('cluster', models.CharField(choices=[('ACS', 'ACS'), ('ANZ', 'ANZ'), ('ASEAN + Japan + Hongkong', 'ASEAN + Japan + Hongkong'), ('CSN', 'CSN'), ('CSS', 'CSS'), ('ESG', 'ESG'), ('Europe + Greece + Israel', 'Europe + Greece + Israel'), ('India North', 'India North'), ('India South', 'India South'), ('India West', 'India West'), ('MEO', 'MEO'), ('NAC + LAD', 'NAC + LAD'), ('NetSuite', 'NetSuite'), ('Saudi + Sub Sahara', 'Saudi + Sub Sahara'), ('Sub Sahara', 'Sub Sahara'), ('UK + IL', 'UK + IL')], max_length=50)),
                ('rdm', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=2)),
                ('status', models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('Active', 'Active'), ('Closed', 'Closed'), ('On-hold', 'On-hold'), ('Dropped', 'Dropped')], default='Yet to Start', max_length=50)),
                ('ownership', models.CharField(choices=[('OC', 'OC Owner'), ('GSC', 'GSC Owned')], default='GSC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=10, unique=True)),
                ('resource_name', models.CharField(max_length=50)),
                ('resource_email', models.EmailField(max_length=50, unique=True)),
                ('resource_primary_skill_1', models.CharField(choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50)),
                ('resource_primary_skill_1_level', models.IntegerField()),
                ('resource_primary_skill_2', models.CharField(blank=True, choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50, null=True)),
                ('resource_primary_skill_2_level', models.IntegerField(blank=True, null=True)),
                ('resource_secondary_skill_1', models.CharField(blank=True, choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50, null=True)),
                ('resource_secondary_skill_1_level', models.IntegerField(blank=True, null=True)),
                ('resource_secondary_skill_2', models.CharField(blank=True, choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50, null=True)),
                ('resource_secondary_skill_2_level', models.IntegerField(blank=True, null=True)),
                ('resource_tertiary_skill_1', models.CharField(blank=True, choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50, null=True)),
                ('resource_tertiary_skill_1_level', models.IntegerField(blank=True, null=True)),
                ('resource_tertiary_skill_2', models.CharField(blank=True, choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50, null=True)),
                ('resource_tertiary_skill_2_level', models.IntegerField(blank=True, null=True)),
                ('resource_miscellaneous_skills', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_role', models.CharField(choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Project Manager', 'Project Manager'), ('Business Analyst', 'Business Analyst'), ('Technical Lead', 'Technical Lead')], max_length=20)),
                ('resource_level', models.IntegerField()),
                ('resource_YOE', models.IntegerField()),
                ('resource_EPM_exp', models.IntegerField()),
                ('resource_location', models.CharField(choices=[('ACS', 'ACS'), ('ANZ', 'ANZ'), ('ASEAN + Japan + Hongkong', 'ASEAN + Japan + Hongkong'), ('CSN', 'CSN'), ('CSS', 'CSS'), ('ESG', 'ESG'), ('Europe + Greece + Israel', 'Europe + Greece + Israel'), ('India North', 'India North'), ('India South', 'India South'), ('India West', 'India West'), ('MEO', 'MEO'), ('NAC + LAD', 'NAC + LAD'), ('NetSuite', 'NetSuite'), ('Saudi + Sub Sahara', 'Saudi + Sub Sahara'), ('Sub Sahara', 'Sub Sahara'), ('UK + IL', 'UK + IL')], max_length=50)),
                ('resource_industry_1', models.CharField(blank=True, choices=[('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=50, null=True)),
                ('resource_industry_2', models.CharField(blank=True, choices=[('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=50, null=True)),
                ('resource_industry_3', models.CharField(blank=True, choices=[('Banking', 'Banking'), ('Insurance', 'Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=50, null=True)),
                ('resource_DOJ', models.CharField(max_length=10)),
                ('resource_exit_date', models.CharField(blank=True, max_length=10, null=True)),
                ('resource_onleave_start_date', models.CharField(blank=True, max_length=10, null=True)),
                ('resource_onleave_end_date', models.CharField(blank=True, max_length=10, null=True)),
                ('resource_isbillable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
                ('resource_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('To-join', 'To-join'), ('On-leave', 'On-leave')], default='To-join', max_length=20)),
                ('resource_availability', models.CharField(blank=True, choices=[('On Bench', 'On Bench'), ('On Project-Full Time', 'On Project-Full Time'), ('On Project-Part Time', 'On Project-Part Time'), ('Blocked', 'Blocked')], default='Available', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Hyperion Planning', 'Hyperion Planning'), ('ARM', 'ARM'), ('HFM', 'HFM'), ('DRM', 'DRM'), ('EPBCS - Capex', 'EPBCS - Capex'), ('EPBCS- WF', 'EPBCS- WF'), ('EPBCS - Project', 'EPBCS - Project'), ('EPBCS -Finance', 'EPBCS -Finance'), ('Strategic Work Force Planning (SWP)', 'Strategic Work Force Planning (SWP)'), ('Strategic Modelling (SM)', 'Strategic Modelling (SM)'), ('Predictive Cash Forecasting (PCF)', 'Predictive Cash Forecasting (PCF)'), ('Predictive Planning (PP)', 'Predictive Planning (PP)'), ('FCCS', 'FCCS'), ('ARCS - RC', 'ARCS - RC'), ('ARCS - TM', 'ARCS - TM'), ('TRCS', 'TRCS'), ('PCMCS', 'PCMCS'), ('EDMCS', 'EDMCS'), ('Narrative Reporting (NR)', 'Narrative Reporting (NR)'), ('Management Reporting (MR)', 'Management Reporting (MR)'), ('FDMEE', 'FDMEE'), ('Data Management (DM)', 'Data Management (DM)')], max_length=50)),
                ('miscellaneous_skills_required', models.CharField(blank=True, max_length=50, null=True)),
                ('role_required', models.CharField(choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Project Manager', 'Project Manager'), ('Business Analyst', 'Business Analyst'), ('Technical Lead', 'Technical Lead')], max_length=20)),
                ('level_required', models.IntegerField()),
                ('number_required', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=20)),
                ('fulfilled_quantity', models.IntegerField(default=0)),
                ('requirement_type', models.CharField(choices=[('Internal', 'Internal'), ('New', 'New'), ('Replacement', 'Replacement'), ('CR', 'CR')], default='New', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizationreport.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('requirement_added', 'Requirement Added'), ('requirement_updated', 'Requirement Updated'), ('requirement_removed', 'Requirement Removed'), ('resource_allocated', 'Resource Allocated'), ('resource_deallocated', 'Resource Deallocated'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_status_changed', 'Project Status Changed')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='utilizationreport.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilizationreport.requirement')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilizationreport.resource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=20)),
                ('allocation_status', models.CharField(choices=[('On Bench', 'On Bench'), ('On Project-Full Time', 'On Project-Full Time'), ('On Project-Part Time', 'On Project-Part Time'), ('Blocked', 'Blocked')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizationreport.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizationreport.requirement')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizationreport.resource')),
            ],
        ),
    ]
