# Generated by Django 5.0.2 on 2025-04-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizationreport', '0002_deal_project_resource_requirement_projectactivitylog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectactivitylog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectactivitylog',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='projectactivitylog',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='projectactivitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='UtilizationReport',
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ProjectActivityLog',
        ),
    ]
