# Generated by Django 5.0.2 on 2025-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataextract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='billing',
            field=models.CharField(max_length=500),
        ),
    ]
