# Generated by Django 5.0.2 on 2025-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataextract', '0003_emailtrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='rdmname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdm_name', models.CharField(max_length=255)),
            ],
        ),
    ]
