# Generated by Django 5.0.2 on 2025-04-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataextract', '0004_rdmname'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizationreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
